parameters:
    database_driver:   pdo_mysql
    database_host:     mysql
    database_port:     ~
    database_name:     wellcommerce
    database_user:     admin
    database_password: admin

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt

    debug_toolbar:          true
    debug_redirects:        false
    use_assetic_controller: true

    doctrine.server_version: 5.6

    fallback_theme: wellcommerce
    fallback_hostname: localhost

    developer_mode.ip: 127.0.0.1

    search_engine: lucene

    php_binary_path: ~

    pdo.db_options:
      db_table:    session
      db_id_col:   session_id
      db_data_col: session_value
      db_time_col: session_time
